name: CI

on: push

jobs:
  build:
    runs-on: ubuntu-18.04
    if: github.event.action != 'closed'
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.ref }}
      - name: Use Node.js 12.16.1
        uses: actions/setup-node@v1
        with:
          node-version: '12.16.1'
      - name: yarn install
        run: yarn install --frozen-lockfile --silent;
      - name: yarn tsc
        run: yarn tsc --noEmit
      - name: yarn test
        run: yarn test
      - name: yarn lint
        run: yarn lint
